package com.example.myapplication;

public class Constantes {
    public static final String ROOT_URL = "http://partiny.000webhostapp.com/";
    public static final String URL_BUSCADOR = ROOT_URL + "fetch_buscador.php";
    public static final String URL_CHAT_LOCAL = ROOT_URL + "fetch_chats_local.php";
    public static final String URL_CHATS_USUARIO = ROOT_URL + "fetch_chats_usuario.php";
    public static final String URL_MENSAJES_CHAT = ROOT_URL + "fetch_mensajes_chat.php";
    public static final String URL_LOGIN = ROOT_URL + "login.php";
    public static final String URL_INSERT_USER = ROOT_URL + "insert_user.php";

    public static final String URL_SITIOS_USUARIO_HA_ESTADO_INICIO =ROOT_URL + "fetch_sitios_ha_estado_inicio.php";

    public static final String URL_SITIOS_USUARIO_HA_ESTADO =ROOT_URL + "fetch_sitios_en_los_que_ha_estado_perfil.php";
    public static final String URL_SITIOS_RECOMENDADOS =ROOT_URL + "fetch_sitios_mas_destacados.php";
    public static final String URL_SITIOS_HAN_ESTADO_SEGUIDOS = ROOT_URL + "fetch_sitios_en_los_que_han_estado_seguidos.php";
    public static final String URL_PUBLICACIONES_INICIO =  ROOT_URL + "fetch_publicaciones_inicio.php" ;
    public static final String URL_FETCH_CHATS_USUARIO = ROOT_URL + "fetch_chats_usuario.php" ;
    public static final String URL_ANADIR_MENSAJE_CHAT = ROOT_URL + "insert_mensaje.php" ;
    public static final String URL_INSERT_USUARIO_CHAT = ROOT_URL + "insert_usuario_chat.php";
    public static final String URL_INFO_LOCAL = ROOT_URL + "fetch_info_local.php";
    public static final String URL_FETCH_RELACIONES_LOCAL = ROOT_URL + "fetch_relaciones_local.php";
    public static final String URL_FETCH_AMIGOS_HAN_IDO_LOCAL =  ROOT_URL + "fetch_amigos_han_ido_local.php";
    public static final String FETCH_EVENTOS_LOCAL = ROOT_URL + "fetch_eventos_local.php";
    public static final String URL_FETCH_USER_EN_CHAT_LOCAL =ROOT_URL + "fetch_si_user_en_chat_local.php";
    public static final String URL_INSERT_USER_VA_A_EVENTO = ROOT_URL + "insert_user_va_a_evento.php";
    public static final String URL_DELETE_FROM_USER_VA_A_EVENTO = ROOT_URL + "Delete_from_user_va_a_evento.php";
    public static final String URL_FETCH_USERS_VAN_A_EVENTO = ROOT_URL + "fetch_users_que_van_a_evento.php";
    public static final String URL_ANADIR_USER_CHAT_LOCAL = ROOT_URL +"insert_usuario_chat_local.php";
    public static final String URL_FETCH_INFO_PARTICIPAR_CHAT_CONCRETO =ROOT_URL + "fetch_info_participar_chat_concreto.php";
    public static final String FETCH_MENSAJES_CHAT_LOCAL = ROOT_URL + "fetch_mensajes_chat_local.php";
    public static final String URL_INSERT_MENSAJE_CHAT_LOCAL = ROOT_URL + "insert_mensajes_chat_local.php" ;
    public static final String URL_FETCH_PUBLICACIONES_USUARIO = ROOT_URL + "fetch_publicaciones_perfil_usuario.php";
    public static final String URL_FETCH_LUGARES_USUARIO =  ROOT_URL + "fetch_sitios_en_los_que_ha_estado_perfil.php" ;
    public static final String URL_FETCH_SEGUIDORES_USUARIO_PERFIL = ROOT_URL + "fetch_seguidores_usuario_perfil.php" ;
    public static final String URL_FETCH_SEGUIDOS_USUARIO_PERFIL = ROOT_URL + "fetch_seguidos_usuario_perfil.php";
    public static final String URL_FETCH_INFO_PUBLICACION = ROOT_URL +  "fetch_info_publicacion.php";
    public static final String URL_PUBLICACIONES_MAS_DESTACADAS = ROOT_URL +  "fetch_publicaciones_mas_destacadas.php";
    public static final String URL_FETCH_LOCALES_BUSQUEDA = ROOT_URL +  "fetch_locales_busqueda.php" ;
    public static final String URL_INSERT_PUBLICACION = ROOT_URL +  "insert_publicacion.php";
    public static final String URL_INSERT_CREAR_CHAT = ROOT_URL +  "insert_chat_crear_chat.php";
    public static final String URL_INSERT_USER_CHAT =  ROOT_URL +  "insert_user_chat_crear_chat.php";
    public static final String URL_FETCH_INFO_EVENTO_CONCRETO = ROOT_URL +  "fetch_info_evento_concreto.php";
    public static final String URL_FETCH_CHATS_LOCAL =ROOT_URL + "fetch_chats_local.php";
    public static final Object URL_ROOT_PERFIL = "http://partiny.000webhostapp.com/perfil/";
    public static final String UPDATE_REGISTRO_CHAT_USER = ROOT_URL+ "update_registro_chat_user.php";
    public static final String URL_INSERT_CHAT_LOCAL = ROOT_URL+"insert_chatLocal.php" ;
    public static final String URL_INSERT_PUNTUACION_LOCAL =  ROOT_URL+ "insert_puntuacion_local.php";
    public static final String URL_INSERT_PUNTUACION_EVENTO =  ROOT_URL+ "insert_puntuacion_evento.php" ;
    public static final String URL_UPDATE_CLICKS_PUBLICACION = ROOT_URL+ "update_publicacion_clicks.php";
    public static final String URL_UPDATE_CLICKS_EVENTO = ROOT_URL+ "update_evento_click.php";
    public static final String URL_UPDATE_CLICKS_LOCAL = ROOT_URL+ "update_locales_click.php";
    public static final String URL_FETCH_SI_USER_SIGUE_A = ROOT_URL+ "fetch_si_user_sigue_a.php";
    public static final String URL_INSERT_SEGUIDOR_SEGUIDO = ROOT_URL+ "insert_seguidor_seguido.php";
    public static final String URL_DELETE_SEGUIDOR_SEGUIDO = ROOT_URL +  "delete_seguidor_seguido.php";
    public static final String URL_FETCH_SI_USER_VA_A_EVENTO = ROOT_URL +  "fetch_si_user_va_a_evento.php";
    public static final String URL_INSERT_USER_HA_ESTADO_LOCAL = ROOT_URL + "insertUserEstadoLocal.php";
    public static final String URL_FETCH_SI_USER_HA_IDO_LOCAL = ROOT_URL + "fetch_si_user_va_a_local.php";
    public static final String URL_DELETE_CHAT_CREAR_CHAT = ROOT_URL + "deleteChatCrearChat.php";
    public static final String URL_UPDATE_DESCRIPCION_USER =  ROOT_URL + "update_perfil_descripcion.php";
    public static final String URL_AUTOCOMPLETE_BUSCADOR = ROOT_URL + "fetch_busqueda_autocomplete.php";
    public static final String URL_UPLOAD_IMAGE_PERFIL = ROOT_URL + "upload_image.php";
}
